cargo-features = ["edition2024"]
[package]
name = "pinocchio-program"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive", "min_const_generics"] }
pinocchio = "0.9.2"
pinocchio-system = "0.3.0"
